/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package majong;

import org.junit.Test;
import static org.junit.Assert.*;

public class MajongMainTest {
    @Test public void testMajongMain() {
        String[] learnArgs = {"-l"};
        MajongMain.main(learnArgs);
        
        String[] runArgs = {"-r path"};
        MajongMain.main(runArgs);
    }
}
