/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package majong.calculate;

import org.junit.Test;
import static org.junit.Assert.*;

public class StructureTest {
    @Test public void testMajongMain() {
		int[] array = {3,3,3,0,0,0,0,0,0, 0,0,1,1,3,0,0,0,0, 0,0,0,0,0,0,0,0,0, 0,0,0,0, 0,0,0};
		Structure s = new Structure();
		s.structure_method(array);
		System.out.println(s.janto);
		System.out.println(s.kotsu);
		System.out.println(s.shuntsu);
		System.out.println(s.flag7);
		System.out.println(s.flag13);

    }
}

